### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by thermo74** [skarab42/marv#12]
Hello, again :)

It seems if I don't open overlay in my navigator obs doesn't print it, it's a astounding issue.
I don't understand how my browser and my obs is related...

After open it on my navigator and clear obs source caches it work.

**Comment by skarab42** [comment]
Hello ;)
For now it can not work both in OBS and your navigator, only one at time.
But normaly you dont need to open your navigator first... ongoing investigation!

**Comment by skarab42** [comment]
Hello!

This can happen if you open OBS before Marv. That's because Marv serves the overlay and OBS can't display it.

I've added a banner that warns the user if the overlay is not reachable.
![overlay_not_connected](https://user-images.githubusercontent.com/62928763/103611456-a0314d00-4f22-11eb-8048-892b0f842031.png)

You don't need to open the overlay in the browser, just configure the browser source in OBS to refresh it. 
![browser_source_options_en](https://user-images.githubusercontent.com/62928763/103611209-171a1600-4f22-11eb-80d9-4594c9a9d393.png)

And if the overlay is not accessible you just have to toggle the visibility of the source to reload it.
![source_visibility](https://user-images.githubusercontent.com/62928763/103611347-63655600-4f22-11eb-89cf-656a2d816443.png)
